export const ADD_COUNTRIES = 'ADD_COUNTRIES'
export const GET_ACTIVITIES = 'GET_ACTIVITIES'
export const GET_COUNTRY_ACTIVITIES = "GET_COUNTRY_ACTIVITIES"
export const SET_COUNTRIES = "SET_COUNTRIES"
export const SET_NAVIGATION = "SET_NAVIGATION"
export const SET_COUNTRIES_CONTROLLED = 'SET_COUNTRIES_CONTROLLED'
export const SET_LOADING = "SET_LOADING"
export const RESET_LOADING = "RESET_LOADING"



